name: Tests

on:
  push:
    branches:
      - feature/vue-3
  pull_request:

jobs:

  Build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm
    - name: Install modules
      run: npm install
    - name: Build the package
      run: npm run build

  Code-Quality:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm
    - name: Install modules
      run: npm install
    - name: Run code quality tests
      run: npm run lint -- --format=compact

  Export-Size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: titouanmathis/export-size-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: npm run build
          paths: dist
